### PR TITLE
Parse Itho autotemp/spider messages

### PR DESCRIPTION
**Pull request by tomkooij**
This is WIP. 

Itho daalderop heatpump "WPU" and UFH "autotemp":
Autotemp is the "controller" of the UFH and heatpump combination. It collects temperatures and decides when to cool/heat. It sends "heat demand" (3110) to the main room spider thermostat, which is connected via wired OT to the heatpump.
The spider sends OT messages/status back to the autotemp UFH over ramses II RF (3EF0 - actuator state). 

3EF0 sent by spider main room thermostat to autotemp UFH valve units. 
Fix 22C9 regex - Itho autotemp UFH (valve unit) sends this reply 
Silence 22D0 AssertionErrors
Add to 4e04 regex
3110 packet heat_demand 3110 from Itho Daalderop Autotemp UFH valve controller

### CODE REVIEW

**Comment by tomkooij** [comment]
I'll implement tests. WIP.

**Comment by tomkooij** [comment]
Ouch, this has become a mess because I left this stale for a while and upstream has changed considerably...

I'll try to figure out which changes are still relevant and problably start a new PR. (With tests...)

**Comment by zxdavb** [comment]
@tomkooij just rebase:
```
git merge upstream/master
```

or similar.

**Comment by zxdavb** [comment]
@tomkooij just rebase:
```
git merge upstream/master
```

or similar.

**Comment by tomkooij** [comment]
```
git merge origin/master
Already up-to-date.
```

I'm not sure what is going on, but I messed up this branch, or something. I'll start over.

**Comment by zxdavb** [comment]
Did you `git fetch --all`?

**Pull request closed without merging**
